import { Platform } from 'react-native';

const strings = {
  writeWay: 'WriteWay',
  brands: 'Brands',
  category: 'Category',
  search: 'Search',
  productList: 'Product List',
  productDetails: 'Product Details',
  shoppingCart: 'Shopping Cart',
  skip: 'Skip',
  login: 'Login',
  email: 'Email',
  password: 'Password',
  oldPassword: 'Old Password',
  newPassword: 'New Password',
  ConfirmNewPassword: 'Confirm New Password',
  firstname: 'Firstname',
  lastname: 'Lastname',
  mobile: 'Mobile Number',
  confirmPassword: 'Confirm Password',
  pinCode: 'Pincode',
  loginButton: 'Log In',
  dontHaveAccount: "Don't have an account? ",
  alreadyHaveAccount: 'Already have an account? ',
  signinHere: 'Sign In Here',
  signup: 'Signup',
  createAccount: 'Create account',
  next: 'Next',
  register: 'Register',
  acceptTC: 'I accept terms and policies',
  discount:
    'Festival discount upto 20% off above 599/-, Free shipping across India',
  viewAllBrand: 'View All Brands',
  viewAllCategories: 'View All Categories',
  exclusiveItems: 'Exclusive Items',
  relatedProduct: 'Related Products',
  specifications: 'Specifications',
  description: 'Description',
  delivery: 'Delivery: Usually Ships in 5 to 7 Bussiness Days',
  expectedDelivery:
    'Expected delivery - Usually Ships in 5 to 7 Bussiness Days',
  productCode: 'Product Code:',
  buyNow: 'Buy Now',
  quntity: 'Quantity:',
  invalidPin: 'Please enter valid Pincode',
  invalidCity: 'Please enter City',
  invalidAddress: 'Please enter address',
  invalidEmail: 'Please enter valid email',
  invalidPassword: 'Please enter password',
  invalidFirstname: 'Please enter Firstname',
  invalidLastname: 'Please enter Lastname',
  invalidMobile: 'Please enter Mobile number',
  mobileLength: 'Please enter 10 digit Mobile number',
  passwordInvalid: 'Please enter Password',
  passwordMismatch: 'Password and Confirm does not match',
  newMismatch: 'New password and Confirm new password does not match',
  oldPasswordInvalid: 'Please enter Old Password',
  newPasswordInvalid: 'Please enter New Password',
  ConfirmNewpasswordInvalid: 'Please enter Confirm new Password',
  price: 'Price',
  total: 'Total',
  itemAdded: 'Product added in cart',
  pleaseLogin: 'Login required for purchase products, please login',
  cancel: 'Cancel',
  logout: 'Logout',
  logoutConfirmation: 'Are you sure you want to logout?',
  myAccount: 'My Account',
  myOrders: 'My Orders',
  myAddress: 'My Addresses',
  changePassword: 'Change Password',
  order: 'Order.',
  qty: 'Qty.',
  subTotal: 'Sub Total',
  shipping: 'Shipping',
  couponDiscount: 'Coupon Discount',
  orderSummary: 'Order Summary',
  city: 'City',
  state: 'State',
  country: 'Country',
  address: 'Address',
  landmark: 'Landmark',
  continue: 'Review and Confirm',
  youSaved: 'You Saved',
  totalCost: 'TOTAL COST(Inc. Tax)',
  typeHere: 'Type Here',
  coupon: 'Coupon',
  apply: 'Apply',
  remove: 'Remove',
  payNow: 'Pay Now',
  submit: 'Submit',
  passwordChanged: 'Password changed successful',
  inCorrectPassword: 'Please enter correct password',
  noInternet: 'No Internet!',
  pleaseCheckInternet: 'Please check your internet connection',
  appUpdate: 'App update required',
  pleaseUpdateApp:
    Platform.OS === 'android'
      ? 'Please update app from the PlayStore'
      : 'Please update app from the AppStore',
  update: 'Update',
  emptySearch: 'Sorry, we cannot find what you are looking for.',
  emptyCart: 'You have no items in your shopping cart',
  clear: 'Clear',
  close: 'CLOSE',
  filters: 'Filters',
  clearAll: 'CLEAR ALL',
};

export default strings;
