import { Platform } from 'react-native';

const strings = {
  thermonic: 'Thermonic',
  search: 'Search',
  login: 'Login',
  email: 'Email',
  product: 'Product',
  category: 'Category',
  subCategory: 'Sub category',
  firstname: 'Firstname',
  lastname: 'Lastname',
  password: 'Password',
  contact: 'Contact',
  company: 'Company Name',
  managerName: 'Manager Name',
  workerName: 'Worker Name',
  dispatcherName: 'Dispatcher Name',
  Address: 'Address',
  website: 'Website',
  otherInfo: 'Other Info',
  loginButton: 'Log In',
  add: 'Add',
  invalidEmail: 'Please enter valid email',
  invalidPassword: 'Please enter password',
  passwordInvalid: 'Please enter Password',
  cancel: 'Cancel',
  logout: 'Logout',
  logoutConfirmation: 'Are you sure you want to logout?',
  clear: 'Clear',
  close: 'CLOSE',
  filters: 'Filters',
  clearAll: 'CLEAR ALL',
  subCategories: `Product's sub categories`,
  addSubCategories: `Add your product's sub categories`,
  acceptOrder: 'Accept Order',
  viewAllOrder: 'View All Order',
  pending: 'Pending Orders',
  inProgress: 'In Progress Orders',
  accepted: 'Accepted Orders',
  dispatched: 'Dispatched Orders',
  pendingOrders: 'Pending Orders',
  categoryAddedSuccess: "Category Added",
  subCategoryAddedSuccess: "Sub Category Added"
};

export default strings;
