import { Platform } from 'react-native';

const strings = {
  thermonic: 'Thermonic',
  search: 'Search',
  login: 'Login',
  email: 'Email',
  product: 'Product',
  category: 'Category',
  subCategory: 'Sub category',
  name: 'Name',
  username: 'Username',
  password: 'Password',
  contact: 'Contact',
  company: 'Company Name',
  managerName: 'Manager Name',
  workerName: 'Worker Name',
  dispatcherName: 'Dispatcher Name',
  Address: 'Address',
  website: 'Website',
  otherInfo: 'Other Info',
  loginButton: 'Log In',
  add: 'Add',
  invalidEmail: 'Please enter valid email',
  invalidPassword: 'Please enter password',
  passwordInvalid: 'Please enter Password',
  cancel: 'Cancel',
  logout: 'Logout',
  logoutConfirmation: 'Are you sure you want to logout?',
  clear: 'Clear',
  close: 'CLOSE',
  filters: 'Filters',
  clearAll: 'CLEAR ALL',
};

export default strings;
